version: "3.7"

services: 
    django1:
        # build: .
        image: stojanov98/cloud_computing:latecontext
        restart: on-failure:10
        ports: 
            - "8000:8000"
        env_file: 
            - ../vagrant/vars.env
        depends_on: 
            - cloud_db1
        volumes: 
            - ./project/:/usr/src/project
        environment: 
            DB_HOST: "cloud_db1"
            DB_NAME: "cloud_db1"
        networks: 
            - cloud_comuting_network
    django2:
        # build: .
        image: stojanov98/cloud_computing:latecontext
        restart: on-failure:10
        ports: 
            - "8001:8000"
        env_file: 
            - ../vagrant/vars.env
        depends_on: 
            - cloud_db2
        volumes: 
            - ./project/:/usr/src/project
        environment: 
            DB_HOST: "cloud_db2"
            DB_NAME: "cloud_db2"
        networks: 
            - cloud_comuting_network
    cloud_db1:
        image: postgres 
        volumes: 
            - postgres_data1:/var/lib/postgresql/data/
        restart: always
        environment: 
            - POSTGRES_USER=admin
            - POSTGRES_PASSWORD=admin
            - POSTGRES_DB=cloud_db1
        # ports: 
        #     - "5435:5432"
        networks: 
            - cloud_comuting_network
    cloud_db2:
        image: postgres 
        volumes: 
            - postgres_data2:/var/lib/postgresql/data/
        restart: always
        environment: 
            - POSTGRES_USER=admin
            - POSTGRES_PASSWORD=admin
            - POSTGRES_DB=cloud_db2
        # ports: 
        #     - "5433:5432"
        networks: 
            - cloud_comuting_network
        
volumes: 
    postgres_data1: 
    postgres_data2:

networks: 
    cloud_comuting_network:
        driver: bridge